version: "3.7"

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always

    ports:
      - 27017:27017

  api:
    image: node:latest
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start

  # frontend:
  #   container_name: frontend
  #   depends_on:
  #     - api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ".:/app"
  #     - "/app/node_modules"
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
